#!/bin/bash

export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin

set -e

if [ "$1" = "install" ]; then
	PROCINFO=$( cat /proc/cpuinfo )

	if [ $( echo "$PROCINFO" | grep -w flags | grep -ic avx ) -eq 0 ]; then
		echo -e "\nThis package can run only on hosts with processors having avx instruction support (Intel Sandybridge (2012) or above).\nProcessor seems to be a very old one. Please install on a machine with a newer processor.\n"
		exit 1
	fi

	KERN_VER=`uname -r`

	KERN_NUM1=$( echo $KERN_VER | awk -F. '{print $1}' )
	KERN_NUM2=$( echo $KERN_VER | awk -F. '{print $2}' )
	KERN_NUM3=$( echo $KERN_VER | awk -F. '{print $3}' | awk -F- '{print $1}' )

	MIN_VER="4.4.0"

	if [ $KERN_NUM1 -lt 4 ]; then
		echo -e "Host Linux Kernel version $KERN_NUM1 is less than minimum $MIN_VER required for partha.\n"
		exit 1
	elif [ $KERN_NUM1 -eq 4 ] && [ $KERN_NUM2 -lt 4 ]; then
		echo -e "Host Linux Kernel version $KERN_NUM1 is less than minimum $MIN_VER required for partha\n"
		exit 1
	fi
fi

exit 0

