#!/bin/bash

export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin

set -e

if [ "$1" = "configure" ]; then
	if ! getent group gyeeta > /dev/null; then
		addgroup --quiet --system gyeeta
	fi

	if ! getent passwd gyeeta > /dev/null; then
		adduser --quiet --system --ingroup gyeeta --home /opt/gyeeta --no-create-home gyeeta
	fi

	if [ ! -f /opt/gyeeta/madhava/cfg/madhava_main.json ]; then
		touch /opt/gyeeta/madhava/cfg/madhava_main.json
		chmod 0660 /opt/gyeeta/madhava/cfg/madhava_main.json
	fi

	chown -h gyeeta:gyeeta /opt/gyeeta

	chown -hR gyeeta:gyeeta /opt/gyeeta/madhava
	
fi

exit 0

